using Beskar.Memory.Code;

namespace Beskar.Memory.Code.Rendering;

/// <summary>
/// Provides extension methods for <see cref="CodeTextWriter"/> to facilitate code generation.
/// </summary>
public static class CodeWriterExtensions
{
   extension(ref CodeTextWriter writer)
   {
      /// <summary>
      /// Writes a nullable directive to the writer, enabling or disabling nullable context.
      /// </summary>
      /// <param name="enable"><c>true</c> to enable nullable context; <c>false</c> to disable it.</param>
      public void WriteEnableNullable(bool enable)
      {
         writer.WriteLine(enable 
            ? "#nullable enable" 
            : "#nullable disable");
         writer.WriteLine();
      }

      /// <summary>
      /// Writes a utilizing namespace directive using the specified expression.
      /// </summary>
      /// <param name="expression">The namespace to import.</param>
      public void WriteUsing(string expression)
      {
         writer.WriteLineInterpolated($"using {expression};");
      }

      /// <summary>
      /// Writes a namespace declaration if the expression is not null.
      /// </summary>
      /// <param name="expression">The name of the namespace to declare, or <c>null</c>.</param>
      public void WriteNamespace(string? expression)
      {
         if (expression is null) return;
         
         writer.WriteLineInterpolated($"namespace {expression};");
         writer.WriteLine();
      }

      /// <summary>
      /// Writes the opening auto-generated tag to the writer.
      /// </summary>
      public void WriteAutoGeneratedOpen()
      {
         writer.WriteLine("// <auto-generated>");
      }
      
      /// <summary>
      /// Writes the closing auto-generated tag followed by an empty line to the writer.
      /// </summary>
      public void WriteAutoGeneratedClose()
      {
         writer.WriteLine("// </auto-generated>");
         writer.WriteLine();
      }
   }
}
