using Beskar.Memory.Code;

namespace Beskar.Memory.Code.Rendering;

public static class CodeWriterExtensions
{
   extension(ref CodeTextWriter writer)
   {
      public void WriteEnableNullable(bool enable)
      {
         writer.WriteLine(enable 
            ? "#nullable enable" 
            : "#nullable disable");
         writer.WriteLine();
      }

      public void WriteUsing(string expression)
      {
         writer.WriteLineInterpolated($"using {expression};");
      }

      public void WriteNamespace(string? expression)
      {
         if (expression is null) return;
         
         writer.WriteLineInterpolated($"namespace {expression};");
         writer.WriteLine();
      }

      public void WriteAutoGeneratedOpen()
      {
         writer.WriteLine("// <auto-generated>");
      }
      
      public void WriteAutoGeneratedClose()
      {
         writer.WriteLine("// </auto-generated>");
         writer.WriteLine();
      }
   }
}

