using Beskar.Memory.Code.Common.Enums;
using Beskar.Memory.Code.Common.Specs;
using Beskar.Memory.Code.Common.Symbols;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code.TypeIdGenerator.Generator.Models;
using Beskar.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.Memory.Code.TypeIdGenerator.Generator.Rendering;

public sealed class TypeIdRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required TypeSafeIdSpec Spec { get; init; }

   private bool _isAnyNumber;
   private bool _isGuid;

   private string _structName = string.Empty;
   private string _underlyingType = string.Empty;
   private string _parameterName = string.Empty;
   
   private TypeSafeIdAttributeSpec _attributeSpec;
   
   protected override string Render()
   {
      InitializeFields();
      
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);
      
      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {TypeIdGenerator.GeneratorName}[{TypeIdGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         WriteUsings(ref writer);
         writer.WriteNamespace(Spec.NamedTargetArchetype.Symbol.NameSpace);
         
         WriteHeader(ref writer);
         writer.OpenBody();
         
         WriteConstantLikeFields(ref writer);
         WriteCheckProperties(ref writer);
         WriteStringify(ref writer);
         WriteEquals(ref writer);
         WriteCompareTo(ref writer);
         WriteCompareOperators(ref writer);
         WriteImplicitOperators(ref writer);
         WriteExplicitOperators(ref writer);
         WriteSpanParsable(ref writer);
         WriteSpanFormattable(ref writer);
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteSpanFormattable(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Span formattable");
      writer.WriteLine("public string ToString(string? format, IFormatProvider? formatProvider)");
      writer.UpIndent();
      writer.WriteLineInterpolated($" => {_parameterName}.ToString(format, formatProvider);");
      writer.DownIndent();
      writer.WriteLine();

      var lastParameter = _isGuid ? "" : ", provider";
      
      writer.WriteLine("public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)");
      writer.UpIndent();
      writer.WriteLineInterpolated($" => {_parameterName}.TryFormat(destination, out charsWritten, format{lastParameter});");
      writer.DownIndent();
   }
   
   private void WriteSpanParsable(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Span parsable interface");
      writer.WriteLineInterpolated($"public static {_structName} Parse(string s, IFormatProvider? provider)");
      writer.UpIndent();
      writer.WriteLine("=> Parse(s.AsSpan(), provider);");
      writer.DownIndent();
      writer.WriteLine();
      
      writer.WriteLineInterpolated($"public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {_structName} result)");
      writer.UpIndent();
      writer.WriteLine("=> TryParse(s.AsSpan(), provider, out result);");
      writer.DownIndent();
      
      writer.WriteLineInterpolated($"public static {_structName} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)");
      writer.UpIndent();
      writer.WriteLineInterpolated($" => new {_structName}({_underlyingType}.Parse(s, provider));");
      writer.DownIndent();
      writer.WriteLine();

      writer.WriteLineInterpolated($"public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {_structName} result)");
      writer.OpenBody();
      
      writer.WriteLineInterpolated($"if ({_underlyingType}.TryParse(s, provider, out var value))");
      writer.OpenBody();
      
      writer.WriteLineInterpolated($"result = new {_structName}(value);");
      writer.WriteLine("return true;");
      
      writer.CloseBody();

      writer.WriteLine("result = default;");
      writer.WriteLine("return false;");
      
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteExplicitOperators(ref CodeTextWriter writer)
   {
      if (!_attributeSpec.AddExplicitConversions || (!_isAnyNumber && !_isGuid))
      {
         return;
      }
      
      writer.WriteLine("// Explicit nullable to non-nullable conversions");
      writer.WriteLineInterpolated($"public static explicit operator {_structName}({_underlyingType}? value) => value.HasValue ? new {_structName}(value.Value) : Empty;");
      writer.WriteLineInterpolated($"public static explicit operator {_underlyingType}({_structName}? id) => id ?? Empty;");
      writer.WriteLine();
   }

   private void WriteImplicitOperators(ref CodeTextWriter writer)
   {
      if (!_attributeSpec.AddImplicitConversions)
      {
         return;
      }

      writer.WriteLine("// Implicit non-nullable conversions");
      writer.WriteLineInterpolated($"public static implicit operator {_structName}({_underlyingType} value) => new(value);");
      writer.WriteLineInterpolated($"public static implicit operator {_underlyingType}({_structName} id) => id.{_parameterName};");
      writer.WriteLine();
      
      writer.WriteLine("// Implicit nullable conversions");
      writer.WriteLineInterpolated($"public static implicit operator {_structName}?({_underlyingType}? value) => value.HasValue ? new(value.Value) : null;");
      writer.WriteLineInterpolated($"public static implicit operator {_underlyingType}?({_structName}? id) => id?.{_parameterName};");
      writer.WriteLine();
      
      writer.WriteLine("// Implicit non-nullable to nullable conversions");
      writer.WriteLineInterpolated($"public static implicit operator {_structName}?({_underlyingType} value) => new(value);");
      writer.WriteLineInterpolated($"public static implicit operator {_underlyingType}?({_structName} id) => id.{_parameterName};");
      writer.WriteLine();
   }

   private void WriteCompareOperators(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Compare operators");

      writer.WriteLineInterpolated($"public static bool operator <({_structName} left, {_structName} right) => left.{_parameterName} < right.{_parameterName};");
      writer.WriteLineInterpolated($"public static bool operator <=({_structName} left, {_structName} right) => left.{_parameterName} <= right.{_parameterName};");
      writer.WriteLineInterpolated($"public static bool operator >({_structName} left, {_structName} right) => left.{_parameterName} > right.{_parameterName};");
      writer.WriteLineInterpolated($"public static bool operator >=({_structName} left, {_structName} right) => left.{_parameterName} >= right.{_parameterName};");
      writer.WriteLine();
   }

   private void WriteCompareTo(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Compareable interfaces");
      writer.WriteLineInterpolated($"public int CompareTo({_structName} other) => {_parameterName}.CompareTo(other.{_parameterName});");
      writer.WriteLine();

      writer.WriteLineInterpolated($"public int CompareTo(ITypeSafeIdentifier<{_underlyingType}>? other) => other switch");
      writer.OpenBody();
      
      writer.WriteLineInterpolated($"null => 1,");
      writer.WriteLineInterpolated($"{_structName} id => {_parameterName}.CompareTo(id.{_parameterName}),");
      writer.WriteLineInterpolated($"_ => throw new ArgumentException($\"Object must be of type {_structName}.\") ");
      
      writer.CloseBodySemicolon();
      writer.WriteLine();
   }

   private void WriteEquals(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Equals and GetHashCode");
      
      writer.WriteLineInterpolated($"public bool Equals({_structName} other) => {_parameterName}.Equals(other.{_parameterName});");
      writer.WriteLineInterpolated($"public bool Equals(ITypeSafeIdentifier<{_underlyingType}>? other) => other is {_structName} id && {_parameterName}.Equals(id.{_parameterName});");
      writer.WriteLineInterpolated($"public override int GetHashCode() => {_parameterName}.GetHashCode();");
      writer.WriteLine();
   }

   private void WriteStringify(ref CodeTextWriter writer)
   {
      writer.WriteLine("// Stringify and debugger view");
      var expression = $"$\"{{nameof({_structName})}}: {{{_parameterName}}}\"";

      if (_attributeSpec.IsOverrideString)
      {
         writer.WriteLineInterpolated($"public override string ToString() => {expression};");
      }
      
      writer.WriteLineInterpolated($"internal string DebuggerView => {expression};");
      writer.WriteLine();
   }

   private void WriteCheckProperties(ref CodeTextWriter writer)
   {
      if (_isAnyNumber || _isGuid)
      {
         return;
      }
      
      writer.WriteLine("// Check properties");
      writer.WriteLineInterpolated($"public bool IsEmpty => {_parameterName}.Equals({_structName}.Empty);");

      if (_isAnyNumber)
      {
         writer.WriteLineInterpolated($"public bool IsMaxValue => {_parameterName}.Equals({_structName}.MaxValue);");
      }
      
      writer.WriteLineInterpolated($"public bool HasValue => !IsEmpty;");
      
      writer.WriteLine();
   }

   private void WriteConstantLikeFields(ref CodeTextWriter writer)
   {
      if (_isAnyNumber || _isGuid)
      {
         writer.WriteLine("// Static constant like fields");
         
         var expression = _isGuid ? "Guid.Empty" : $"({_underlyingType})0";
         writer.WriteLineInterpolated($"public static {_structName} Empty {{ get; }} = new({expression});");
      }

      if (_isAnyNumber)
      {
         writer.WriteLineInterpolated($"public static {_structName} MaxValue {{ get; }} = new({_underlyingType}.MaxValue);");
      }

      if (_isAnyNumber || _isGuid)
      {
         writer.WriteLine();
      }
   }

   private void WriteHeader(ref CodeTextWriter writer)
   {
      var access = Spec.NamedTargetArchetype.Symbol.Accessibility.ToKeywordString();
      
      writer.WriteLine("[StructLayout(LayoutKind.Sequential)]");
      writer.WriteLine("[DebuggerDisplay(\"{DebuggerView,nq}\")]");

      if (_attributeSpec is { AddJsonConverter: true, IsSpanParsable: true })
      {
         writer.WriteLineInterpolated($"[JsonConverter(typeof(TypeSafeIdJsonConverter<{_structName}, {_underlyingType}>))]");
      }
      
      writer.WriteLineInterpolated($"{access} readonly partial record struct {_structName}");
      writer.UpIndent();
      
      writer.WriteLineInterpolated($": IComparable<{_structName}>, ISpanParsable<{_structName}>, ITypeSafeIdentifier<{_underlyingType}>, ISpanFormattable");
      writer.DownIndent();
   }

   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteUsing("System.Diagnostics");
      writer.WriteUsing("System.Diagnostics.CodeAnalysis");
      writer.WriteUsing("System.Runtime.InteropServices");
      writer.WriteUsing("System.Text.Json.Serialization");
      writer.WriteUsing("Beskar.Memory.Code.TypeIdGenerator.Interfaces");
      writer.WriteUsing("Beskar.Memory.Code.TypeIdGenerator.Converters");
      writer.WriteLine();
   }

   private void InitializeFields()
   {
      var named = Spec.NamedTargetArchetype;
      _structName = named.Symbol.Name;
      
      var parameter = named.NamedType.Methods.Array[0].Method.Parameters.Array[0];
      _underlyingType = parameter.Parameter.Type.Symbol.FullName;
      _parameterName = parameter.Symbol.Name;

      _isGuid = parameter.Parameter.Type.Symbol.IsGuid;
      _isAnyNumber = parameter.Parameter.Type.Type.SpecialType.IsAnyNumber;
      
      _attributeSpec = Spec.AttributeSpec;
   }
}