extern alias Generator;

using System.Threading.Tasks;
using System.Linq;
using Xunit;
using Beskar.Memory.Code.TypeIdGenerator.Attributes;
using Beskar.Memory.Code.TypeIdGenerator.Tests.Constants;
using Beskar.Memory.Tests.Utils;

namespace Beskar.Memory.Code.TypeIdGenerator.Tests.Common;

public sealed class SimpleTests
{
   [Fact]
   public void UnderlyingInt()
   {
      var result = Compilations.Create()
         .AddTestScenario("Scenarios/Simple")
         .WithReferenceByType<TypeSafeIdAttribute>()
         .AddSourceGenerator(new Generator::Beskar.Memory.Code.TypeIdGenerator.Generator.TypeIdGenerator())
         .Create();

      var compilation = result.Compilation;

      Assert.Empty(result.Diagnostics);
      Assert.Empty(result.GeneratedDiagnostics);
      Assert.NotEmpty(result.GeneratedSyntaxTrees);

      var generatedSource = result.GeneratedSyntaxTrees.First(t => !t.FilePath.EndsWith("TypeIdGenerator.g.cs")).ToString();
      Assert.Contains("// This file is auto-generated by TypeIdGenerator[1.6.3].", generatedSource);
   }

   [Fact]
   public void UnderlyingIntWithLowercaseValueParameter()
   {
      var source = """
                   using Beskar.Memory.Code.TypeIdGenerator.Attributes;

                   namespace TestNamespace;

                   [TypeSafeId]
                   public readonly partial record struct ExampleLowercaseId(int value);
                   """;

      var result = Compilations.Create()
         .AddSourceText(source)
         .WithReferenceByType<TypeSafeIdAttribute>()
         .AddSourceGenerator(new Generator::Beskar.Memory.Code.TypeIdGenerator.Generator.TypeIdGenerator())
         .Create();

      Assert.Empty(result.Diagnostics);
      Assert.Empty(result.GeneratedDiagnostics);
      Assert.NotEmpty(result.GeneratedSyntaxTrees);

      var generatedSource = result.GeneratedSyntaxTrees.First(t => !t.FilePath.EndsWith("TypeIdGenerator.g.cs")).ToString();
      Assert.Contains("public static implicit operator int(ExampleLowercaseId id) => id.value;", generatedSource);
      Assert.Contains("// This file is auto-generated by TypeIdGenerator[1.6.3].", generatedSource);
   }
}
