using Beskar.Memory.Code.Common.Archetypes;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code.PacketGenerator.Generator.Models;
using Beskar.Memory.Code;
using Beskar.Memory.Collections;
using Beskar.Memory.Code.Models.Symbols.Archetypes;
using Microsoft.CodeAnalysis;

namespace Beskar.Memory.Code.PacketGenerator.Generator.Rendering;

public sealed class PacketRegistryRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required PacketRegistrySpec RegistrySpec { get; init; }
   public required SequenceArray<PacketSpec> PacketSpecs { get; init; }
   public required SequenceArray<int> PacketIndices { get; init; }
   
   private HashSet<int> _indexLookup = [];
   
   protected override string Render()
   {
      _indexLookup = new HashSet<int>(PacketIndices.Array);
      
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {PacketGenerator.GeneratorName}[{PacketGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         WriteUsings(ref writer);
         writer.WriteNamespace(RegistrySpec.NamedTypeArchetype.Symbol.NameSpace);
         
         WriteHeader(ref writer);
         WriteConstructor(ref writer);
         WriteRegisterHandler(ref writer);
         WriteRoutePacket(ref writer);
         
         writer.CloseBody();
         writer.WriteLine();

         WriteCollections(ref writer);
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteRoutePacket(ref CodeTextWriter writer)
   {
      var stateType = RegistrySpec.StateTypeFullName ?? "object";
      writer.WriteLine("public override ValueTask<RoutePacketResult> RoutePacket(");
      writer.UpIndent();
      writer.WriteLineInterpolated($"ref {stateType} state,");
      writer.WriteLine("scoped in ReadOnlySequence<byte> sequence, CancellationToken cancellationToken = default)");
      writer.DownIndent();
      writer.OpenBody();
      
      writer.WriteLine("var reader = new SequenceReader<byte>(sequence);");
      writer.WriteLine("if (!reader.TryReadLittleEndian(out int packetId))");
      writer.OpenBody();
      writer.WriteLine("return ValueTask.FromResult(RoutePacketResult.NotEnoughData);");
      writer.CloseBody();
      writer.WriteLine();
      
      writer.WriteLine("if (packetId < 0 || packetId >= _handlers.Length)");
      writer.OpenBody();
      writer.WriteLine("return ValueTask.FromResult(RoutePacketResult.UnknownPacket);");
      writer.CloseBody();
      writer.WriteLine();
      
      writer.WriteLine("ref var arrayPointer = ref MemoryMarshal.GetArrayDataReference(_handlers);");
      writer.WriteLine("var handlerCollection = Unsafe.Add(ref arrayPointer, (nint)packetId);");
      
      writer.WriteLine("return handlerCollection.Handle(ref state, ref reader, cancellationToken);");
      writer.CloseBody();
   }
    
    private void WriteRegisterHandler(ref CodeTextWriter writer)
    {
      var stateType = RegistrySpec.StateTypeFullName ?? "object";
      writer.WriteLineInterpolated($"public bool RegisterHandler<TPacket>(PacketHandler<{stateType}, TPacket> handler)");
      writer.UpIndent();
      writer.WriteLine("where TPacket : IPacket");
      writer.DownIndent();
      writer.OpenBody();
      
      writer.WriteLine("var packetId = PacketMetadata<TPacket>.Identifier;");
      writer.WriteLine("var handlerCollection = _handlers[packetId];");
      writer.WriteLine();
      
      writer.WriteLineInterpolated($"if (handlerCollection is not IPacketHandlerCollection<{stateType}, TPacket> handlerCollectionTyped)");
      writer.UpIndent();
      writer.WriteLine("return false;");
      writer.DownIndent();

      writer.WriteLine();
      writer.WriteLine("handlerCollectionTyped.RegisterHandler(handler);");
      writer.WriteLine("return true;");
      
      writer.CloseBody();
      writer.WriteLine();
   }
   
   private void WriteConstructor(ref CodeTextWriter writer)
   {
      var registry = RegistrySpec;
      var namedType = registry.NamedTypeArchetype;
      var stateType = RegistrySpec.StateTypeFullName ?? "object";
      
      writer.WriteLineInterpolated($"public {namedType.Symbol.Name}(");
      writer.UpIndent();
      
      var args = namedType.Type.BaseType?.NamedType.Methods.Array is { Length: > 0 } arr
         ? arr[0].Method.Parameters.Array
         : [];
      var argNames = args.Select(x => x.Symbol.Name).ToArray();
      
      for (var index = 0; index < args.Length; index++)
      {
         var arg = args[index];
         var type = arg.Parameter.Type;
         
         writer.WriteLineInterpolated($"{type.Symbol.FullName}? {arg.Symbol.Name} = null{(index == args.Length - 1 ? "" : ",")}");
      }

      writer.DownIndent();
      writer.WriteLineInterpolated($") : base({string.Join(", ", argNames)})");
      writer.OpenBody();
      
      writer.WriteLine("_handlers = [");
      writer.UpIndent();
      
      foreach (var spec in SortPackets(PacketSpecs.Array))
      {
         if (_indexLookup.Contains(spec.OriginalIndex))
         {
            writer.WriteLineInterpolated($"new {GetHandlerCollectionClassName(spec.Spec.NamedTypeArchetype)}(this),");
         }
         else
         {
            writer.WriteLineInterpolated($"new PlaceholderPacketHandlerCollection<{stateType}, {spec.Spec.NamedTypeArchetype.Symbol.FullName}>(this),");
         }
      }
      
      writer.DownIndent();
      writer.WriteLine("];");
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteHeader(ref CodeTextWriter writer)
   {
      var registry = RegistrySpec;
      var namedType = registry.NamedTypeArchetype;
      var stateType = RegistrySpec.StateTypeFullName ?? "object";
      
      writer.WriteLineInterpolated($"{namedType.GetClassStructModifiersString(true)} {namedType.Symbol.Name}");
      writer.OpenBody();

      writer.WriteLineInterpolated($"private readonly IPacketHandlerCollection<{stateType}>[] _handlers;");
      writer.WriteLine();
   }

   private void WriteCollections(ref CodeTextWriter writer)
   {
      var registry = RegistrySpec.NamedTypeArchetype;
      var stateType = RegistrySpec.StateTypeFullName ?? "object";

      for (var index = 0; index < PacketSpecs.Array.Length; index++)
      {
         var spec = PacketSpecs.Array[index];
         var arch = spec.NamedTypeArchetype;

         if (!_indexLookup.Contains(index))
         {
            continue;
         }

         writer.WriteLineInterpolated(
            $"file sealed class {GetHandlerCollectionClassName(arch)}({registry.Symbol.Name} registry)");
         writer.UpIndent();

         writer.WriteLineInterpolated($": BasePacketHandlerCollection<{stateType}, {arch.Symbol.FullName}>(registry);");
         writer.DownIndent();

         writer.WriteLine();
      }
   }

   private static void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System.Buffers");
      writer.WriteUsing("System.Threading.Tasks");
      writer.WriteUsing("System.Threading");
      writer.WriteUsing("System.Runtime.CompilerServices");
      writer.WriteUsing("System.Runtime.InteropServices");
      
      writer.WriteUsing("Beskar.Memory.Code.PacketGenerator.Common");
      writer.WriteUsing("Beskar.Memory.Code.PacketGenerator.Interfaces");
      writer.WriteUsing("Beskar.Memory.Code.PacketGenerator.Models");
      
      writer.WriteLine();
   }
   
   private static IEnumerable<(PacketSpec Spec, int OriginalIndex)> SortPackets(IEnumerable<PacketSpec> packets)
   {
      return packets.Select((spec, index) => (spec, index))
         .OrderBy(x => x.spec.NamedTypeArchetype.Symbol.FullName);
   }

   private static string GetHandlerCollectionClassName(NamedTypeSymbolArchetype archetype)
   {
      if (archetype.NamedType.Arity == 0)
      {
         return $"{archetype.Symbol.Name}HandlerCollection";
      }

      var clean = archetype.Symbol.FullName;
      if (clean.StartsWith("global::"))
         clean = clean[8..];

      clean = clean.Replace(":", "_")
         .Replace(".", "_")
         .Replace("<", "_")
         .Replace(">", "_")
         .Replace("[", "_")
         .Replace("]", "_")
         .Replace("?", "_")
         .Replace(" ", "")
         .Replace(",", "_");

      return $"{clean}HandlerCollection";
   }
}
