using System.Collections.Immutable;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code.ObserveGenerator.Generator.Models;
using Beskar.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Beskar.Memory.Code.ObserveGenerator.Generator.Rendering;

public sealed class ExtensionRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required ImmutableArray<ObserveSpec> Specs { get; init; }

   public required string Namespace { get; init; }

   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ObserveGenerator.GeneratorName}[{ObserveGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         writer.WriteUsing("System.Collections.Immutable");
         writer.WriteLine();

         writer.WriteNamespace($"{Namespace}.ObserveExtensions");

         writer.WriteLine("internal static class ObserveRegistry");
         writer.OpenBody();
         
         writer.WriteLine("public static readonly ImmutableArray<string> GeneratedSourceNames = ImmutableArray.CreateRange<string>([");
         writer.UpIndent();
         
         foreach (var spec in Specs.Where(x => x.ActivitySpec is not null))
         {
            var activityName = SymbolDisplay.FormatLiteral(spec.ActivitySpec?.Name ?? "", true);
            writer.WriteLineInterpolated($"{activityName},");
         }

         writer.DownIndent();
         writer.WriteLine("]);");
         writer.WriteLine();
         
         writer.WriteLine("public static readonly ImmutableArray<string> GeneratedMeterNames = ImmutableArray.CreateRange<string>([");
         writer.UpIndent();

         foreach (var spec in Specs.Where(x => x.MeterSpec is not null))
         {
            var meterName = SymbolDisplay.FormatLiteral(spec.MeterSpec?.Name ?? "", true);
            writer.WriteLineInterpolated($"{meterName},");
         }
         writer.DownIndent();
         writer.WriteLine("]);");
         
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }
}
