using Beskar.Memory.Code.Common.Archetypes;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code.ObserveGenerator.Generator.Models;
using Beskar.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Beskar.Memory.Code.ObserveGenerator.Generator.Rendering;

public sealed class ObserveRenderer(SourceProductionContext ctx) 
   : CodeRenderer(ctx)
{
   public required ObserveSpec Spec { get; init; }

   private string _className = string.Empty;
   
   protected override string Render()
   {
      InitializeFields();
      
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {ObserveGenerator.GeneratorName}[{ObserveGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         WriteUsings(ref writer);
         writer.WriteNamespace(Spec.NamedTypeArchetype.Symbol.NameSpace);

         WriteClass(ref writer);
         WriteInstrumentation(ref writer);
         
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteClass(ref CodeTextWriter writer)
   {
      var spec = Spec.NamedTypeArchetype;
      
      writer.WriteLineInterpolated($"{spec.GetClassStructModifiersString(true)} {_className}{spec.GetGenericParametersString()}");
      writer.OpenBody();

      if (Spec.ActivitySpec is not null)
      {
         writer.WriteLineInterpolated($"private static readonly ActivitySource ActivitySource = {_className}Instrumentation.ActivitySource;");
      }

      if (Spec.MeterSpec is not null)
      {
         writer.WriteLineInterpolated($"private static readonly Meter MeterSource = {_className}Instrumentation.MeterSource;");
      }
      
      writer.WriteLine();
      
      foreach (var instrument in Spec.InstrumentSpecs)
      {
         var (type, method) = GetInstrumentationNames(instrument);
         writer.WriteLineInterpolated($"private static readonly {type}<{instrument.TypeFullName}> {instrument.PropertyName} = {_className}Instrumentation.{instrument.PropertyName};");
      }
      
      writer.CloseBody();
      writer.WriteLine();
   }
   
   private void WriteInstrumentation(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"internal static class {_className}Instrumentation");
      writer.OpenBody();

      if (Spec.ActivitySpec is { } activity)
      {
         var activityName = SymbolDisplay.FormatLiteral(activity.Name, true);
         writer.WriteLineInterpolated($"public static readonly ActivitySource ActivitySource = new({activityName}, \"{activity.Version}\");");
      }

      if (Spec.MeterSpec is { } meter)
      {
         var meterName = SymbolDisplay.FormatLiteral(meter.Name, true);
         writer.WriteLineInterpolated($"public static readonly Meter MeterSource = new({meterName}, \"{meter.Version}\");");
      }

      writer.WriteLine();

      foreach (var instrument in Spec.InstrumentSpecs)
      {
         var (type, method) = GetInstrumentationNames(instrument);
         
         var instrumentName = SymbolDisplay.FormatLiteral(instrument.Name, true);
         var instrumentDescription = instrument.Description is null ? "null" : SymbolDisplay.FormatLiteral(instrument.Description, true);
         var instrumentUnit = instrument.Unit is null ? "null" : SymbolDisplay.FormatLiteral(instrument.Unit, true);
         
         writer.WriteLineInterpolated($"public static readonly {type}<{instrument.TypeFullName}> {instrument.PropertyName} = MeterSource.{method}<{instrument.TypeFullName}>({instrumentName}, {instrumentUnit}, {instrumentDescription});");
      }
      
      writer.CloseBody();
   }

   private (string Type, string Method) GetInstrumentationNames(ObserveInstrumentSpec spec)
   {
      return spec.InstrumentFullName switch
      {
         "Beskar.Memory.Code.ObserveGenerator.Enums.InstrumentKind.Counter" => ("Counter", "CreateCounter"),
         "Beskar.Memory.Code.ObserveGenerator.Enums.InstrumentKind.Gauge" => ("Gauge", "CreateGauge"),
         "Beskar.Memory.Code.ObserveGenerator.Enums.InstrumentKind.Histogram" => ("Histogram", "CreateHistogram"),
         "Beskar.Memory.Code.ObserveGenerator.Enums.InstrumentKind.UpDownCounter" => ("UpDownCounter", "CreateUpDownCounter"),
         _ => throw new InvalidOperationException($"Unknown instrument kind: {spec.InstrumentFullName}")
      };
   }
   
   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System.Diagnostics");
      writer.WriteUsing("System.Diagnostics.Metrics");
      writer.WriteLine();
   }

   private void InitializeFields()
   {
      _className = Spec.NamedTypeArchetype.Symbol.Name;
   }
}
