using Beskar.Memory.Code.EnumGenerator.Generator.Models;
using Beskar.Memory.Code.Common.Enums;
using Beskar.Memory.Code.Models.Symbols.Archetypes;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code;
using Microsoft.CodeAnalysis;

namespace Beskar.Memory.Code.EnumGenerator.Generator.Rendering;

public sealed class EnumExtensionRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required FastEnumSpec Spec { get; init; }
   
   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);
         
         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {EnumGenerator.GeneratorName}[{EnumGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();
         
         writer.WriteUsing("System");
         writer.WriteLine();
         var spec = Spec.NamedType;
         writer.WriteNamespace(spec.Symbol.NameSpace);
                  
         writer.WriteLineInterpolated($"{spec.Symbol.Accessibility.ToKeywordString()} static partial class {spec.Symbol.Name}Extensions");
         writer.OpenBody();

         writer.WriteLineInterpolated($"extension({spec.Symbol.FullName} value)");
         writer.OpenBody();
         
         var fields = spec.NamedType.Fields.Array;
         
         writer.WriteLineInterpolated($"public static int ValueCount => {fields.Length};");
         writer.WriteLine();
         
         WriteAllValues(ref writer, fields);
         WriteAllNames(ref writer, fields);
         
         WriteToFastString(ref writer, fields);
         WriteIsFastDefined(ref writer, fields);
         WriteTryFastParseExact(ref writer, fields);
         WriteTryFastParseCase(ref writer, fields);
         
         writer.CloseBody();
         writer.CloseBody();
         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteAllValues(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public static {Spec.NamedType.Symbol.FullName}[] GetAllValues() => [");
      writer.UpIndent();

      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"{Spec.NamedType.Symbol.FullName}.{field.Symbol.Name},");
      }

      writer.DownIndent();
      writer.WriteLine("];");
      writer.WriteLine();
   }

   private void WriteAllNames(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public static string[] GetAllNames() => [");
      writer.UpIndent();

      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"nameof({Spec.NamedType.Symbol.FullName}.{field.Symbol.Name}),");
      }

      writer.DownIndent();
      writer.WriteLine("];");
      writer.WriteLine();
   }
   
   private void WriteTryFastParseCase(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public static bool TryFastParseCase(string? name, out {Spec.NamedType.Symbol.FullName} result, StringComparison comparisonType = StringComparison.OrdinalIgnoreCase)");
      writer.OpenBody();
      
      writer.WriteLine("switch (name)");
      writer.OpenBody();
      
      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"case string str when str.Equals(nameof({Spec.NamedType.Symbol.FullName}.{field.Symbol.Name}), comparisonType):");
         writer.UpIndent();
         writer.WriteLineInterpolated($"result = {Spec.NamedType.Symbol.FullName}.{field.Symbol.Name};");
         writer.WriteLine("return true;");
         writer.DownIndent();
      }
      
      writer.WriteLine("default:");
      writer.UpIndent();
      writer.WriteLine("result = default;");
      writer.WriteLine("return false;");
      writer.DownIndent();
      
      writer.CloseBodySemicolon();
      writer.CloseBody();
      writer.WriteLine();
   }
   
   private void WriteTryFastParseExact(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public static bool TryFastParseExact(string? name, out {Spec.NamedType.Symbol.FullName} result)");
      writer.OpenBody();
      
      writer.WriteLine("switch (name)");
      writer.OpenBody();
      
      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"case nameof({Spec.NamedType.Symbol.FullName}.{field.Symbol.Name}):");
         writer.UpIndent();
         writer.WriteLineInterpolated($"result = {Spec.NamedType.Symbol.FullName}.{field.Symbol.Name};");
         writer.WriteLine("return true;");
         writer.DownIndent();
      }
      
      writer.WriteLine("default:");
      writer.UpIndent();
      writer.WriteLine("result = default;");
      writer.WriteLine("return false;");
      writer.DownIndent();
      
      writer.CloseBodySemicolon();
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteIsFastDefined(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public bool IsFastDefined()");
      writer.OpenBody();
      
      writer.WriteLine("return value switch");
      writer.OpenBody();
      
      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"{Spec.NamedType.Symbol.FullName}.{field.Symbol.Name} => true,");
      }
      writer.WriteLine("_ => false");
      
      writer.CloseBodySemicolon();
      writer.CloseBody();
      writer.WriteLine();
   }
   
   private void WriteToFastString(ref CodeTextWriter writer, FieldSymbolArchetype[] fields)
   {
      writer.WriteLineInterpolated($"public string ToFastString()");
      writer.OpenBody();

      writer.WriteLine("return value switch");
      writer.OpenBody();

      foreach (var field in fields)
      {
         writer.WriteLineInterpolated($"{Spec.NamedType.Symbol.FullName}.{field.Symbol.Name} => nameof({Spec.NamedType.Symbol.FullName}.{field.Symbol.Name}),");
      }
      
      writer.WriteLine("_ => value.ToString()");
         
      writer.CloseBodySemicolon();
      writer.CloseBody();
      writer.WriteLine();
   }
}
