using System;
using Xunit;
using Beskar.Memory.Code;
using Beskar.Memory.Code.Rendering;

namespace Beskar.Memory.Code.Tests.Rendering
{
   public class CodeWriterExtensionsTests
   {
      [Fact]
      public void WriteEnableNullable_True_WritesEnableAndEmptyLine()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteEnableNullable(true);

         var expected = "#nullable enable\n\n";
         Assert.Equal(expected, writer.ToString());
      }

      [Fact]
      public void WriteEnableNullable_False_WritesDisableAndEmptyLine()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteEnableNullable(false);

         var expected = "#nullable disable\n\n";
         Assert.Equal(expected, writer.ToString());
      }

      [Fact]
      public void WriteUsing_WritesUsingStatement()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteUsing("System.Collections.Generic");

         var expected = "using System.Collections.Generic;\n";
         Assert.Equal(expected, writer.ToString());
      }

      [Fact]
      public void WriteNamespace_NullExpression_DoesNothing()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteNamespace(null);

         Assert.Equal("", writer.ToString());
      }

      [Fact]
      public void WriteNamespace_ValidExpression_WritesNamespaceAndEmptyLine()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteNamespace("Beskar.Memory.Code.Generated");

         var expected = "namespace Beskar.Memory.Code.Generated;\n\n";
         Assert.Equal(expected, writer.ToString());
      }

      [Fact]
      public void WriteAutoGeneratedOpenAndClose_WritesStandardHeaders()
      {
         Span<char> buffer = stackalloc char[256];
         var writer = new CodeTextWriter(buffer);

         writer.WriteAutoGeneratedOpen();
         writer.Write("Content");
         writer.WriteLine();
         writer.WriteAutoGeneratedClose();

         var expected = "// <auto-generated>\nContent\n// </auto-generated>\n\n";
         Assert.Equal(expected, writer.ToString());
      }
   }
}
