using System;
using System.Collections.Generic;
using System.Linq;
using Beskar.Memory.Code.Rendering;
using Beskar.Memory.Code.Models.Symbols.Archetypes;
using Beskar.Memory.Code;
using Beskar.Memory.Code.TypeIdGenerator.Generator.Models;
using Microsoft.CodeAnalysis;

namespace Beskar.Memory.Code.TypeIdGenerator.Generator.Rendering;

public sealed class SerializationRenderer(SourceProductionContext ctx)
   : CodeRenderer(ctx)
{
   public required SerializeSpec Spec { get; init; }

   protected override string Render()
   {
      var writer = new CodeTextWriter(
         stackalloc char[512], stackalloc char[128]);

      try
      {
         writer.WriteEnableNullable(true);

         writer.WriteAutoGeneratedOpen();
         writer.WriteLineInterpolated($"// This file is auto-generated by {SerializationGenerator.GeneratorName}[{SerializationGenerator.GeneratorVersion}].");
         writer.WriteAutoGeneratedClose();

         WriteUsings(ref writer);
         writer.WriteNamespace(Spec.TypeArchetype.Symbol.NameSpace);

         WriteSerializerClass(ref writer);

         writer.WriteLine();
         WriteModuleInitializer(ref writer);

         return writer.WrittenSpan.ToString();
      }
      finally
      {
         writer.Dispose();
      }
   }

   private void WriteUsings(ref CodeTextWriter writer)
   {
      writer.WriteUsing("System");
      writer.WriteUsing("System.Buffers");
      writer.WriteUsing("System.Buffers.Binary");
      writer.WriteUsing("System.Diagnostics.CodeAnalysis");
      writer.WriteUsing("System.Runtime.CompilerServices");
      writer.WriteUsing("Beskar.Memory.Extensions");
      writer.WriteUsing("Beskar.Memory.Buffers");
      writer.WriteUsing("Beskar.Memory.Writers");
      writer.WriteUsing("Beskar.Memory.Serialization.Interfaces");
      writer.WriteUsing("Beskar.Memory.Serialization");
      writer.WriteLine();
   }

   private void WriteSerializerClass(ref CodeTextWriter writer)
   {
      var decl = GetSerializerClassDeclaration();
      writer.WriteLine(decl);
      writer.UpIndent();
      WriteConstraints(ref writer, Spec.TypeArchetype);
      writer.DownIndent();

      writer.OpenBody();

      WriteWriteMethod(ref writer);
      WriteTryReadMethod(ref writer);
      WriteCalculateByteLengthMethod(ref writer);

      writer.CloseBody();
   }

   private string GetTargetTypeString()
   {
      var symbol = Spec.TypeArchetype.Symbol;
      var baseName = symbol.FullName;
      if (Spec.IsOpenGeneric)
      {
         var typeParams = string.Join(", ", Spec.TypeArchetype.NamedType.TypeParameters.Array.Select(x => x.Symbol.Name));
         baseName = $"{symbol.FullName}<{typeParams}>";
      }
      return Spec.TypeArchetype.Type.IsValueType ? baseName : $"{baseName}?";
   }

   private string GetSerializerClassName()
   {
      var name = Spec.TypeArchetype.Symbol.Name;
      return $"{name}Serializer";
   }

   private string GetSerializerClassDeclaration()
   {
      var name = GetSerializerClassName();
      var target = GetTargetTypeString();

      if (Spec.IsOpenGeneric)
      {
         var typeParams = string.Join(", ", Spec.TypeArchetype.NamedType.TypeParameters.Array.Select(x => x.Symbol.Name));
         return $"public sealed class {name}<{typeParams}> : ISerializer<{target}>";
      }
      return $"public sealed class {name} : ISerializer<{target}>";
   }

   private void WriteConstraints(ref CodeTextWriter writer, NamedTypeSymbolArchetype archetype)
   {
      if (archetype.NamedType.Arity == 0) return;

      foreach (var tp in archetype.NamedType.TypeParameters.Array)
      {
         var parts = new List<string>();
         var spec = tp.TypeParameter;

         if (spec.HasUnmanagedTypeConstraint) parts.Add("unmanaged");
         else if (spec.HasValueTypeConstraint) parts.Add("struct");
         else if (spec.HasReferenceTypeConstraint) parts.Add("class");
         else if (spec.HasNotNullConstraint) parts.Add("notnull");

         foreach (var constraintType in spec.ConstraintTypes.Array)
         {
            parts.Add(constraintType.Symbol.FullName);
         }

         if (spec.HasConstructorConstraint) parts.Add("new()");
         if (spec.AllowsRefLikeType) parts.Add("allows ref struct");

         if (parts.Count > 0)
         {
            writer.WriteLineInterpolated($"where {tp.Symbol.Name} : {string.Join(", ", parts)}");
         }
      }
   }

    private void WriteWriteMethod(ref CodeTextWriter writer)
    {
       var target = GetTargetTypeString();
       writer.WriteLineInterpolated($"public static int Write(ref BufferWriter<byte> writer, scoped in {target} value)");
       writer.OpenBody();

       if (!Spec.TypeArchetype.Type.IsValueType)
       {
          writer.WriteLine("if (value is null)");
          writer.OpenBody();
          if (Spec.UnionSpecs.Array.Length > 0)
          {
             writer.WriteLine("(0).WriteLittleEndian(ref writer);");
             writer.WriteLine("return sizeof(int);");
          }
          else
          {
             writer.WriteLine("writer.Add((byte)0);");
             writer.WriteLine("return 1;");
          }
          writer.CloseBody();
          writer.WriteLine();

          if (Spec.UnionSpecs.Array.Length > 0)
          {
             foreach (var union in Spec.UnionSpecs.Array)
             {
                var unionType = union.Type.Symbol.FullName;
                var unionTypeNullable = union.Type.Type.IsValueType ? unionType : $"{unionType}?";
                writer.WriteLineInterpolated($"if (value is {unionType} child{union.Tag})");
                writer.OpenBody();
                writer.WriteLineInterpolated($"({union.Tag}).WriteLittleEndian(ref writer);");
                writer.WriteLineInterpolated($"return sizeof(int) + SerializerRegistry<{unionTypeNullable}>.GetWrite()(ref writer, child{union.Tag});");
                writer.CloseBody();
             }
             writer.WriteLine("throw new InvalidOperationException($\"Unknown union type: {value.GetType()}\");");
             writer.CloseBody();
             return;
          }
          else
          {
             writer.WriteLine("writer.Add((byte)1);");
          }
       }
       else
       {
          if (Spec.UnionSpecs.Array.Length > 0)
          {
             foreach (var union in Spec.UnionSpecs.Array)
             {
                var unionType = union.Type.Symbol.FullName;
                var unionTypeNullable = union.Type.Type.IsValueType ? unionType : $"{unionType}?";
                writer.WriteLineInterpolated($"if (value is {unionType} child{union.Tag})");
                writer.OpenBody();
                writer.WriteLineInterpolated($"({union.Tag}).WriteLittleEndian(ref writer);");
                writer.WriteLineInterpolated($"return sizeof(int) + SerializerRegistry<{unionTypeNullable}>.GetWrite()(ref writer, child{union.Tag});");
                writer.CloseBody();
             }
             writer.WriteLine("throw new InvalidOperationException($\"Unknown union type: {value.GetType()}\");");
             writer.CloseBody();
             return;
          }
       }

       if (Spec.ImplementsSerializationCallback)
       {
          writer.WriteLine("value.OnBeforeSerialize();");
          writer.WriteLine();
       }

       if (Spec.MemberSpecs.Array.Length > 0)
       {
          // Count references to each member type (only those using default registry serializers)
          var typeCounts = new Dictionary<string, int>();
          foreach (var member in Spec.MemberSpecs.Array)
          {
             if (member.SerializerType is null)
             {
                var typeName = GetMemberTypeName(member.Name);
                typeCounts[typeName] = typeCounts.TryGetValue(typeName, out var count) ? count + 1 : 1;
             }
          }

          // Emitted cache variables
          var cachedVars = new Dictionary<string, string>(); // typeName -> varName
          foreach (var kvp in typeCounts)
          {
             if (kvp.Value > 1)
             {
                var varName = $"write{GetSanitizedVariableName(kvp.Key)}";
                writer.WriteLineInterpolated($"var {varName} = SerializerRegistry<{kvp.Key}>.GetWrite();");
                cachedVars[kvp.Key] = varName;
             }
          }
          if (cachedVars.Count > 0)
          {
             writer.WriteLine();
          }

          writer.WriteLine("var bytesWritten = 0;");
          for (var i = 0; i < Spec.MemberSpecs.Array.Length; i++)
          {
             var member = Spec.MemberSpecs.Array[i];
             var memberTypeName = GetMemberTypeName(member.Name);

             if (member.SerializerType is not null)
             {
                var customSerializer = member.SerializerType.Value.Symbol.FullName;
                writer.WriteLineInterpolated($"bytesWritten += {customSerializer}.Write(ref writer, value.{member.Name});");
             }
             else
             {
                if (cachedVars.TryGetValue(memberTypeName, out var varName))
                {
                   writer.WriteLineInterpolated($"bytesWritten += {varName}(ref writer, value.{member.Name});");
                }
                else
                {
                   writer.WriteLineInterpolated($"bytesWritten += SerializerRegistry<{memberTypeName}>.GetWrite()(ref writer, value.{member.Name});");
                }
             }
          }

          if (!Spec.TypeArchetype.Type.IsValueType)
          {
             writer.WriteLine("return bytesWritten + 1;");
          }
          else
          {
             writer.WriteLine("return bytesWritten;");
          }
       }
       else
       {
          writer.WriteLine(!Spec.TypeArchetype.Type.IsValueType ? "return 1;" : "return 0;");
       }

       writer.CloseBody();
       writer.WriteLine();
    }

   private void WriteTryReadMethod(ref CodeTextWriter writer)
   {
      var target = GetTargetTypeString();
      writer.WriteLineInterpolated($"public static bool TryRead(ref SequenceReader<byte> reader, [MaybeNullWhen(false)] out {target} value)");
      writer.OpenBody();

      if (!Spec.TypeArchetype.Type.IsValueType)
      {
         if (Spec.UnionSpecs.Array.Length > 0)
         {
            writer.WriteLine("if (!reader.TryReadLittleEndian(out int tag))");
            writer.OpenBody();
            writer.WriteLine("value = default;");
            writer.WriteLine("return false;");
            writer.CloseBody();
            writer.WriteLine();

            writer.WriteLine("if (tag == 0)");
            writer.OpenBody();
            writer.WriteLine("value = default;");
            writer.WriteLine("return true;");
            writer.CloseBody();
            writer.WriteLine();

            foreach (var union in Spec.UnionSpecs.Array)
            {
               var unionType = union.Type.Symbol.FullName;
               writer.WriteLineInterpolated($"if (tag == {union.Tag})");
               writer.OpenBody();
               writer.WriteLineInterpolated($"if (!SerializerRegistry<{unionType}>.GetTryRead()(ref reader, out var child))");
               writer.OpenBody();
               writer.WriteLine("value = default;");
               writer.WriteLine("return false;");
               writer.CloseBody();
               writer.WriteLine("value = child;");
               writer.WriteLine("return true;");
               writer.CloseBody();
            }

            writer.WriteLine("throw new InvalidOperationException($\"Unknown union tag: {tag}\");");
            writer.CloseBody();
            return;
         }
         else
         {
            writer.WriteLine("if (!reader.TryRead(out byte hasValue))");
            writer.OpenBody();
            writer.WriteLine("value = default;");
            writer.WriteLine("return false;");
            writer.CloseBody();
            writer.WriteLine();

            writer.WriteLine("if (hasValue == 0)");
            writer.OpenBody();
            writer.WriteLine("value = default;");
            writer.WriteLine("return true;");
            writer.CloseBody();
            writer.WriteLine();
         }
      }
      else
      {
         if (Spec.UnionSpecs.Array.Length > 0)
         {
            writer.WriteLine("if (!reader.TryReadLittleEndian(out int tag))");
            writer.OpenBody();
            writer.WriteLine("value = default;");
            writer.WriteLine("return false;");
            writer.CloseBody();
            writer.WriteLine();

            foreach (var union in Spec.UnionSpecs.Array)
            {
               var unionType = union.Type.Symbol.FullName;
               writer.WriteLineInterpolated($"if (tag == {union.Tag})");
               writer.OpenBody();
               writer.WriteLineInterpolated($"if (!SerializerRegistry<{unionType}>.GetTryRead()(ref reader, out var child))");
               writer.OpenBody();
               writer.WriteLine("value = default;");
               writer.WriteLine("return false;");
               writer.CloseBody();
               writer.WriteLine("value = child;");
               writer.WriteLine("return true;");
               writer.CloseBody();
            }

            writer.WriteLine("throw new InvalidOperationException($\"Unknown union tag: {tag}\");");
            writer.CloseBody();
            return;
         }
      }

      // Count references to each member type (only those using default registry serializers)
      var typeCounts = new Dictionary<string, int>();
      foreach (var member in Spec.MemberSpecs.Array)
      {
         if (member.SerializerType is null)
         {
            var typeName = GetMemberTypeName(member.Name);
            typeCounts[typeName] = typeCounts.TryGetValue(typeName, out var count) ? count + 1 : 1;
         }
      }

      // Emitted cache variables
      var cachedVars = new Dictionary<string, string>(); // typeName -> varName
      foreach (var kvp in typeCounts)
      {
         if (kvp.Value > 1)
         {
            var varName = $"read{GetSanitizedVariableName(kvp.Key)}";
            writer.WriteLineInterpolated($"var {varName} = SerializerRegistry<{kvp.Key}>.GetTryRead();");
            cachedVars[kvp.Key] = varName;
         }
      }
      if (cachedVars.Count > 0)
      {
         writer.WriteLine();
      }

      for (int i = 0; i < Spec.MemberSpecs.Array.Length; i++)
      {
         var member = Spec.MemberSpecs.Array[i];
         var memberTypeName = GetMemberTypeName(member.Name);
         var varName = $"member_{member.Name}";

         if (member.SerializerType is not null)
         {
            var customSerializer = member.SerializerType.Value.Symbol.FullName;
            writer.WriteLineInterpolated($"if (!{customSerializer}.TryRead(ref reader, out var {varName}))");
         }
         else
         {
            if (cachedVars.TryGetValue(memberTypeName, out var cachedVar))
            {
               writer.WriteLineInterpolated($"if (!{cachedVar}(ref reader, out var {varName}))");
            }
            else
            {
               writer.WriteLineInterpolated($"if (!SerializerRegistry<{memberTypeName}>.GetTryRead()(ref reader, out var {varName}))");
            }
         }

         writer.OpenBody();
         writer.WriteLine("value = default;");
         writer.WriteLine("return false;");
         writer.CloseBody();
      }

      if (Spec.MemberSpecs.Array.Length > 0)
      {
         writer.WriteLine();
      }

      if (Spec.IsUseConstructor)
      {
         var paramList = new List<string>();
         foreach (var memberIndex in Spec.ConstructorParameterIndices.Array)
         {
            var m = Spec.MemberSpecs.Array[memberIndex];
            paramList.Add($"member_{m.Name}");
         }
         var instantiationTarget = target.EndsWith("?") ? target.Substring(0, target.Length - 1) : target;
         writer.WriteLineInterpolated($"value = new {instantiationTarget}({string.Join(", ", paramList)});");

         var matchedMemberIndices = new HashSet<int>(Spec.ConstructorParameterIndices.Array);
         for (var i = 0; i < Spec.MemberSpecs.Array.Length; i++)
         {
            if (!matchedMemberIndices.Contains(i))
            {
               var m = Spec.MemberSpecs.Array[i];
               writer.WriteLineInterpolated($"value.{m.Name} = member_{m.Name};");
            }
         }
      }
      else
      {
         var instantiationTarget = target.EndsWith("?") ? target.Substring(0, target.Length - 1) : target;
         writer.WriteLineInterpolated($"value = new {instantiationTarget}();");
         foreach (var m in Spec.MemberSpecs.Array)
         {
            writer.WriteLineInterpolated($"value.{m.Name} = member_{m.Name};");
         }
      }

      if (Spec.ImplementsSerializationCallback)
      {
         writer.WriteLine();
         writer.WriteLine("value.OnAfterDeserialize();");
      }

      writer.WriteLine();
      writer.WriteLine("return true;");
      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteCalculateByteLengthMethod(ref CodeTextWriter writer)
   {
      var target = GetTargetTypeString();
      writer.WriteLineInterpolated($"public static int CalculateByteLength(scoped in {target} value)");
      writer.OpenBody();

      if (!Spec.TypeArchetype.Type.IsValueType)
      {
         writer.WriteLine("if (value is null)");
         writer.OpenBody();
         if (Spec.UnionSpecs.Array.Length > 0)
         {
            writer.WriteLine("return sizeof(int);");
         }
         else
         {
            writer.WriteLine("return 1;");
         }
         writer.CloseBody();
         writer.WriteLine();

         if (Spec.UnionSpecs.Array.Length > 0)
         {
            foreach (var union in Spec.UnionSpecs.Array)
            {
               var unionType = union.Type.Symbol.FullName;
               writer.WriteLineInterpolated($"if (value is {unionType} child{union.Tag})");
               writer.OpenBody();
               writer.WriteLineInterpolated($"return sizeof(int) + SerializerRegistry<{unionType}>.GetCalculateByteLength()(child{union.Tag});");
               writer.CloseBody();
            }
            writer.WriteLine("throw new InvalidOperationException($\"Unknown union type: {value.GetType()}\");");
            writer.CloseBody();
            return;
         }
      }
      else
      {
         if (Spec.UnionSpecs.Array.Length > 0)
         {
            foreach (var union in Spec.UnionSpecs.Array)
            {
               var unionType = union.Type.Symbol.FullName;
               writer.WriteLineInterpolated($"if (value is {unionType} child{union.Tag})");
               writer.OpenBody();
               writer.WriteLineInterpolated($"return sizeof(int) + SerializerRegistry<{unionType}>.GetCalculateByteLength()(child{union.Tag});");
               writer.CloseBody();
            }
            writer.WriteLine("throw new InvalidOperationException($\"Unknown union type: {value.GetType()}\");");
            writer.CloseBody();
            return;
         }
      }

      if (Spec.MemberSpecs.Array.Length > 0)
      {
         var typeCounts = new Dictionary<string, int>();
         foreach (var member in Spec.MemberSpecs.Array)
         {
            if (member.SerializerType is null)
            {
               var typeName = GetMemberTypeName(member.Name);
               typeCounts[typeName] = typeCounts.TryGetValue(typeName, out var count) ? count + 1 : 1;
            }
         }

         // Emitted cache variables
         var cachedVars = new Dictionary<string, string>(); // typeName -> varName
         foreach (var kvp in typeCounts)
         {
            if (kvp.Value > 1)
            {
               var varName = $"calc{GetSanitizedVariableName(kvp.Key)}";
               writer.WriteLineInterpolated($"var {varName} = SerializerRegistry<{kvp.Key}>.GetCalculateByteLength();");
               cachedVars[kvp.Key] = varName;
            }
         }
         if (cachedVars.Count > 0)
         {
            writer.WriteLine();
         }

         writer.WriteLine("var totalLength = 0;");
         for (var i = 0; i < Spec.MemberSpecs.Array.Length; i++)
         {
            var member = Spec.MemberSpecs.Array[i];
            var memberTypeName = GetMemberTypeName(member.Name);

            if (member.SerializerType is not null)
            {
               var customSerializer = member.SerializerType.Value.Symbol.FullName;
               writer.WriteLineInterpolated($"totalLength += {customSerializer}.CalculateByteLength(value.{member.Name});");
            }
            else
            {
               if (cachedVars.TryGetValue(memberTypeName, out var cachedVar))
               {
                  writer.WriteLineInterpolated($"totalLength += {cachedVar}(value.{member.Name});");
               }
               else
               {
                  writer.WriteLineInterpolated($"totalLength += SerializerRegistry<{memberTypeName}>.GetCalculateByteLength()(value.{member.Name});");
               }
            }
         }

         if (!Spec.TypeArchetype.Type.IsValueType)
         {
            writer.WriteLine("return totalLength + 1;");
         }
         else
         {
            writer.WriteLine("return totalLength;");
         }
      }
      else
      {
         writer.WriteLine(!Spec.TypeArchetype.Type.IsValueType ? "return 1;" : "return 0;");
      }

      writer.CloseBody();
      writer.WriteLine();
   }

   private void WriteModuleInitializer(ref CodeTextWriter writer)
   {
      writer.WriteLineInterpolated($"file static class {Spec.TypeArchetype.Symbol.Name}SerializerInitializer");
      writer.OpenBody();
      writer.WriteLine("[System.Runtime.CompilerServices.ModuleInitializer]");
      writer.WriteLine("internal static void Initialize()");
      writer.OpenBody();

      if (Spec.IsOpenGeneric)
      {
         var targetOpen = GetOpenGenericTypeSyntax(Spec.TypeArchetype.Symbol.FullName, Spec.TypeArchetype.NamedType.Arity);
         var serializerOpen = GetOpenGenericTypeSyntax(GetSerializerClassName(), Spec.TypeArchetype.NamedType.Arity);
         writer.WriteLineInterpolated($"SerializerRegistry.RegisterOpenGeneric({targetOpen}, {serializerOpen});");
      }
      else
      {
         var target = Spec.TypeArchetype.Symbol.FullName;
         if (!Spec.TypeArchetype.Type.IsValueType)
         {
            target = $"{target}?";
         }
         var serializer = GetSerializerClassName();
         writer.WriteLineInterpolated($"SerializerRegistry<{target}>.Register<{serializer}>();");
      }

      writer.CloseBody();
      writer.CloseBody();
   }

   private string GetOpenGenericTypeSyntax(string baseName, int arity)
   {
      if (arity == 0) return $"typeof({baseName})";
      var commas = new string(',', arity - 1);
      return $"typeof({baseName}<{commas}>)";
   }

   private string GetMemberTypeName(string name)
   {
      foreach (var p in Spec.TypeArchetype.NamedType.Properties.Array)
      {
         if (p.Symbol.Name == name)
         {
            return p.Property.Type.Symbol.FullName;
         }
      }
      foreach (var f in Spec.TypeArchetype.NamedType.Fields.Array)
      {
         if (f.Symbol.Name == name)
         {
            return f.Field.Type.Symbol.FullName;
         }
      }
      return "object";
   }

   private string GetSanitizedVariableName(string typeName)
   {
      var clean = typeName;

      if (clean.StartsWith("global::"))
         clean = clean[8..];

      clean = clean.Replace(".", "")
         .Replace("<", "")
         .Replace(">", "")
         .Replace("[", "")
         .Replace("]", "")
         .Replace("?", "")
         .Replace(" ", "")
         .Replace(",", "");

      return clean;
   }
}
